### ISSUE TITLE
var-Funktion rechnet falsch

### ISSUE THREAD

**Issue by ukalina** [behrenle/arithmico#153]
Die Stochastik-Funktion var für die Varianz rechnet momentan mit der Formel für die 
**technische Varianz**  s_^2 = 1/(n-1) * \sum_{i=1}^n (x_i - m)^2 
statt mit der (im Schulunterricht üblichen und dort einfach als Varianz bezeichneten) 
**Stichprobenvarianz** s^2 =1/n * \sum_{i=1}^n (x_i - m)^2  
Beispiel Berechnet werden soll die (Stichproben-)Varianz der Liste 1 ; 3 ; 5 ; 9 ; 12, also 
\sigma ^2 = ((1-6)^2 + (3-6)^2 + (5-6)^2 + (9-6)^2 + (12-6)^2))/5 = (25 + 9 + 1 + 9 + 36)/5 = 80/5 =16 
 
Arithmico:
Eingabe: var(1;3;5;9;12)
Ausgabe:  20
Hier wird die Summe der quadratischen Abweichungen offensichtlich durch 4 statt durch 5 geteilt.
var sollte mit der Stichprobenvarianz (durch n teilen) rechnen.

Erklärung des Unterschieds auf  https://de.quora.com/Was-ist-der-Unterschied-zwischen-Varianz-und-Stichprobenvarianz-Wieso-sind-die-Formeln-anders

**Comment by behrenle** [comment]
Danke für den Hinweis. Da hab ich wohl ein bisschen zu schnell implementiert :sweat_smile:

**Comment by behrenle** [comment]
Wurde in #161 gefixt und wird zusammen mit dem `1.0` Release ausgerollt
