### ISSUE TITLE
Hilfe-Text zu table-Befehl

### ISSUE THREAD

**Issue by ukalina** [behrenle/arithmico#157]
Der Hilfe-Text zu table-Befehl sollte verständlicher formuliert werden. Vorschlagl: 
table(f, u?, v?, w?)	Erstellt  zu der Funktion f eine Wertetabelle mit Wertepaaren [x; f(x)] für  x-Werte aus dem Intervall [u; v]. Dabei gibt w die Schrittweite der x-Werte an.

**Comment by behrenle** [comment]
Wurde in #163 gefixt. Ich habe deinen Vorschlag genau so übernommen. Wird zusammen mit der 1.0 ausgerollt
