### ISSUE TITLE
nsolve liefert Doppellösung

### ISSUE THREAD

**Issue by ukalina** [behrenle/arithmico#158]
Eingabe: nsolve(x^3 +x^2 -17*x +15 =0)
Ausgabe: [-5; -5; 1; 3]
-5 ist aber nur eine einfache Lösung.

**Comment by behrenle** [comment]
das ist leider bedingt durch numerisches rauschen :/ ich schaue mal, ob ich da ein bisschen was an der Ergebnisaufbereitung drehen kann vielleicht hat @tirextech auch ein paar Ideen dazu

**Comment by behrenle** [comment]
wurde in #166 gefixt und wird mit der 1.0 ausgerollt
