### ISSUE TITLE
Support more Latex commands

### ISSUE THREAD

**Issue by behrenle** [behrenle/arithmico#265]
### Trigonometrische Funktionen
- [x] `\sin`
- [x] `\cos`
- [x] `\tan`
- [x] `\arcsin` -> `asin(...)`
- [x] `\arccos` -> `acos(...)`
- [x] `\arctan` -> `atan(...)`

### Hyperbolische Funktionen
- [x] `\sinh`
- [x] `\cosh`
- [x] `\tanh`

### Andere Funktionen
- [x] `\min`
- [x] `\max`
- [x] `\gcd { ... , ... }` -> `gcd(... , ...)`

### Verschiedenes
Folgende Features sollte man vorher nochmal diskutieren, ob sie sinnvoll sind:
- vertikal skalierbare klammern mit `\left(` und `\right)`
- vektoren mit `\vec` sind glaube ich nicht sinnvoll, da sie in Latex nur für die Pfeile über dem Symbol sorgen

**Comment by opensource25** [comment]
Ich werde die Funktionen implementieren.

**Comment by opensource25** [comment]
weitere Latex Ausdrücke:

- [ ] `\pi`
- [ ] `b^{x}` zum Beispiel `b^{-2}` oder `b^{18}`

**Comment by behrenle** [comment]
ja, die Potenzen sind auch eine gute Idee
