### ISSUE TITLE
windows local installation fails due to linux commands in build script

### ISSUE THREAD

**Issue by gepp4** [behrenle/arithmico#310]
Hello, I forked the project and tried to install it locally to my pc with Windows, but the `build` script located at `arithmico\libs\engine\package.json` failed, since it contains linux commands. 

I solved the issue by replacing it with:
` "build": "rd /s /q lib && npm run build:types && npm run build:js" `

It might be useful considering using a build script based on the OS. A possible solution could be [run-script-os](https://www.npmjs.com/package/run-script-os)

**Comment by tirextech** [comment]
Hi,
we implemented a node script like behrenle had suggested. So the build process should work os independent. The fix is now available at dev.
