### ISSUE TITLE
Collection of points Meeting BBI of 14.2.23

### ISSUE THREAD

**Issue by cssbue** [behrenle/arithmico#319]
- Tastenkombinationen für alle Schalter und für "Protokoll in die Zwischenablage" zumindest aber für Rechner, Einstellungen und Hilfe

- Das Eingabefeld soll auch als Suchfeld für Funktionen dienen, so wie im TE oder im Browser Eingabefeld

- Navigation in den Einstellungen und in der Hilfe ohne Rahmen. Mit Braille funktioniert die Navigation!

- Der Ausgabetext eines Schalters auf der Braillezeile sollen die Kurztasten angezeigt werden.

- Beim Überfliegen des Mauszeigers sollen auch die Kurztasten angezeigt werden.

- Bogenmaß als Befehl wäre schön. Dann muss man für eine Ausgabe nicht extra die Einstellungen ändern.

- Ableitungen/Integrale von Funktionen! Nicht nur in einem Punkt! Notwendig für Österreich!

- Tippfehler in der Hilfe: bei cosh und tanh fehlt das "u" im Wort hyperbolicus

- Matrizen werden in Österreich Zeilenweise ein.- und ausgegeben. In Arithmico Spaltenweise. Hier braucht es in den Einstellungen einen Schalter zum Umstellen

- Graphen hörbar machen, siehe DESMOS.com, das wäre schön.

- Koeffizient und Variable soll auch ohne * geschrieben werden dürfen. zB 3x statt 3*x

The key combination Ctrl-Alt-I is assigned twice. When the Windows screen magnifier is activated, it is used to invert the colour. This double assignment is unfavourable. After a short test, an alternative assignment could be:
Ctrl-I : Focus input and delete content
Alt-I : Focus input.

It might make sense to implement further key assignments. This would be practical for the function "Save protocol", and possibly for other buttons.

The following function areas are not yet fully mapped. Details will follow: Statistics

As far as operability is concerned, it is noticeable or desired:
Do not use the explicit paint character. What are the sources of errors?

Initialising the calculator with a string or parameters, for example to be able to use country-specific notations or to increase ease of use:
bruch(x):=fraction(x)
wurzel(x):=sqrt(x)
Overloading of operators: wurzel(x,y)

This could be done, for example, by importing a definition set. There could be a standard definition that is imported if it exists.

**Comment by cssbue** [comment]
This could be done, for example, by importing a definition set. There could be a standard definition that is imported if it exists.

**Comment by behrenle** [comment]
no aliases.

**Comment by behrenle** [comment]
bitte in einzeltickets umwandeln
